### ISSUE TITLE
我想照着您的代码自己实现一份bitarray，如果最后成功了会加上mit协议，可以吗

### ISSUE THREAD

**Issue by csh0101** [tunabay/go-bitarray#7]
很荣幸可以看到这份代码。

**Comment by tunabay** [comment]
Of course, this project is open sourced, so you can copy and/or modify it as long as you follow the MIT license.
(I can't read/write Chinese, so I read it with Google Translate. I may have misunderstood the intent of your question.)

**Comment by csh0101** [comment]
Thanks，you understand is right。
